name: Start Build (KSU)

on:
  workflow_dispatch:

env:
  DEFCONFIG: vendor/spes-perf_defconfig
  ARCH: arm64
  SUBARCH: arm64
  KERNEL_NAME: Chrysalis Kernel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Set up Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl lld llvm flex g++-multilib gcc-multilib git gnupg gperf lib32readline-dev lib32z1-dev lz4 libncurses5-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 libelf-dev binutils-aarch64-linux-gnu

    - name: Download Clang Toolchain
      run: |
        mkdir -p clang
        cd clang
        curl -LO https://github.com/ZyCromerZ/Clang/releases/download/16.0.6-20260807-release/Clang-16.0.6-20260807.tar.gz
        tar -xf Clang-16.0.6-20260807.tar.gz --strip-components=1
        cd ..

    - name: Prepare Toolchain Environment
      run: |
        CLANG_BIN=$(readlink -f $(find $(pwd)/clang -type d -name "bin" | head -n 1))
        echo "$CLANG_BIN" >> $GITHUB_PATH

    - name: Compile kernel
      run: |
        export ARCH=${{ env.ARCH }}
        export SUBARCH=${{ env.SUBARCH }}
        
        sed -i 's/local short/return 0/g' scripts/setlocalversion     
        curl -LSs "https://raw.githubusercontent.com/yuksk-cyber/KernelSU-Next/refs/heads/legacy-susfs/kernel/setup.sh" | bash -s legacy-susfs
        curl -LSs "https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/mainline/Patches/syscall_hook_patches.sh" | bash -s mainline
        curl -LSs "https://raw.githubusercontent.com/xxblebleblexx/nomount-installer/refs/heads/installer/nomount.sh" | bash -s 4.19
        echo "CONFIG_KSU=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_MANUAL_HOOK=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_NEXT=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_NOMOUNT=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> arch/${{ env.ARCH }}/configs/${{ env.DEFCONFIG }}

        
        make O=out ARCH=arm64 ${{ env.DEFCONFIG }}
        make O=out ARCH=arm64 olddefconfig
        
        make -j$(nproc --all) CC=clang O=out ARCH=arm64 LLVM=1 LLVM_IAS=1 LD=ld.lld AS=llvm-as AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump READELF=llvm-readelf STRIP=llvm-strip CROSS_COMPILE=aarch64-linux-gnu-
        
        mkdir -p build_artifacts
        find out/arch/${{ env.ARCH }}/boot/ -maxdepth 1 -type f \( -name "Image.gz" -o -name "dtbo.img" \) -exec cp {} ./build_artifacts/ \;

        if [ -z "$(ls -A build_artifacts)" ]; then
          echo "ERROR: Required kernel artifacts (Image.gz, dtbo.img) not found! Build failed."
          exit 1
        fi

    - name: Check results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_NAME }}-Artifacts
        path: build_artifacts/*
